# Generated by Django 4.1.3 on 2022-11-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=120)),
                ('region_name', models.CharField(max_length=120)),
                ('available_profiles', models.CharField(max_length=120)),
                ('access_key', models.CharField(max_length=120)),
                ('secret_access_key', models.CharField(max_length=120)),
            ],
        ),
    ]
