# Generated by Django 4.1.3 on 2022-11-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountconfiguration',
            name='available_profiles',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accountconfiguration',
            name='profile_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accountconfiguration',
            name='region_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
