# Generated by Django 4.1.3 on 2022-12-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_alter_accountconfiguration_available_profiles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountconfiguration',
            old_name='available_profiles',
            new_name='arn',
        ),
        migrations.RenameField(
            model_name='accountconfiguration',
            old_name='profile_name',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='accountconfiguration',
            name='user_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
