# Generated by Django 4.1.3 on 2022-12-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0003_rename_available_profiles_accountconfiguration_arn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountconfiguration',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
